build:
  stage: build
  image: klakegg/hugo:0.81.0-ext-alpine-ci
  script:
    - hugo
  artifacts:
    paths:
      - public/
  # only:
  #   - master@noalino/my_portfolio

deploy:
  stage: deploy
  image: klakegg/hugo:0.81.0-ext-alpine-ci
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -Cr -P 59100 -o StrictHostKeyChecking=no public/* benoit@benoitgelineau.com:~/portfolio
  # only:
  #   - master@noalino/my_portfolio
