version: '3'

services:
  dev:
    image: klakegg/hugo:0.101.0-ext-alpine
    command: server --disableFastRender
    volumes:
      - .:/src
    ports:
      - 1313:1313
  build:
    image: klakegg/hugo:0.101.0-ext-alpine
    volumes:
      - .:/src
    ports:
      - 1313:1313
